### ISSUE TITLE
Final lmdb file for ImageNet?

### ISSUE THREAD

**Issue by he-y** [Lyken17/Efficient-PyTorch#11] opened 2019-09-16 07:27 UTC
Great work.
Could you provide the final lmdb file for ImageNet?

**Comment by Lyken17** [comment] 2019-09-16 08:11
It might be hard. No cloud drive provides a fast yet stable download for ~100Gb file.

If you have original imagenet available locally, you can generate the lmdb via

```
python folder2lmdb.py --folder $IMAGENET_ROOT --name train
```

**Comment by he-y** [comment] 2019-09-16 08:22
Thanks.
I have got the lmdb file from the above commander.

But during training, I meet the [msgpack error](https://github.com/Lyken17/Efficient-PyTorch/issues/3).
After solving the problem with the [reply](https://github.com/Lyken17/Efficient-PyTorch/issues/3#issuecomment-429162654).

I meet another error:

> File "pruning_imagenet_lmdb.py", line 741, in <module>
    main()
  File "pruning_imagenet_lmdb.py", line 177, in main
    num_workers=args.workers, pin_memory=True, sampler=None)
  File "/data/yahe/anaconda3/envs/pt1.2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/data/yahe/anaconda3/envs/pt1.2/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 92, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/data/yahe/anaconda3/envs/pt1.2/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 100, in num_samples
    return len(self.data_source)
TypeError: 'bytes' object cannot be interpreted as an integer




I'm not sure if the LMDB is correct. Do you have any idea about this?
System:
Pytorch =1.2 
torchvision=0.4 
![image](https://user-images.githubusercontent.com/10541284/64943390-2e9d3d80-d89e-11e9-943a-1acbfad8c58d.png)

**Comment by Lyken17** [comment] 2019-09-16 22:47
That's weird. Not sure what the exact cause is. Can you try [tensorpack's way to dump lmdb](https://github.com/tensorpack/benchmarks/blob/master/ImageNet/dump-lmdb.py)?

**Comment by he-y** [comment] 2019-09-18 02:16
Thanks.
Do the raw images be processed by the [facebook process](https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#download-the-imagenet-dataset)?
Or just directly extracted from source tar file?

**Comment by Lyken17** [comment] 2019-09-18 03:29
Original source images are dumped into the lmdb, in order to be more flexible for difference preprocesses.

**Comment by Lyken17** [comment] 2019-09-18 03:29
Does tensorpack's script solve your problem?

**Comment by he-y** [comment] 2019-09-18 04:18
Facebook process create a list of directory and move the image of the same class into one folder, which might be the reason of error. 
I will try original image without process later.

**Comment by Lyken17** [comment] 2019-09-18 04:46
My script is based on `torchvision.datasets.ImageFolder`, which requires validation to be pre-processed by fb scripts.

**Comment by Fangyh09** [comment] 2019-10-15 14:58
@he-y You can try this https://github.com/Fangyh09/Image2LMDB which is based on this project and fix some small problems.

**Comment by HaoerSlayer** [comment] 2019-12-04 14:18
Cool!
This really works but I`m not sure if the error occured is normal when I set num_workers>0 ?
 I can only run that with num_workers=0

**Comment by Lyken17** [comment] 2019-12-28 09:21
@MorningstarZhang Can you share the detailed error log?

@he-y @Fangyh09 I have uploaded final lmdbs on academic torrents. You are welcome to try and share feedback. 

[Training lmdb]( https://academictorrents.com/details/d58437a61c1adf9801df99c6a82960d076cb7312/tech)
[Val lmdb](https://academictorrents.com/details/207ebd69f80a3707f035cd91a114466a270e044d/tech)

**Comment by HaoerSlayer** [comment] 2019-12-28 09:53
@Lyken17 
Thanks.
My problem has been tackled by initializing ImageFolderLMDB.env in function __getitem__() instead of function __init__() as the code used to be. I`m not sure if it was caused by some modification that I 
 made. It seems that no one else met the same trouble.  Here is the error log if it would be helpful.

C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\python.exe D:/Users/Administrator/PycharmProjects/Image2LMDB-master/test_lmdb.py
Traceback (most recent call last):
  File "D:/Users/Administrator/PycharmProjects/Image2LMDB-master/test_lmdb.py", line 59, in <module>
    for index, data in enumerate(trainloader):
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\my_root\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle Environment objects

**Comment by Lyken17** [comment] 2019-12-28 19:59
@MorningstarZhang Seems your problem is related with `_MultiProcessingDataLoaderIter`. This is a known issue for windows platform. Can you try set num_workers to 0 ?

**Comment by HaoerSlayer** [comment] 2019-12-29 02:00
@Lyken17 
Nothing goes wrong if num_workers is set to 0.

**Comment by Lyken17** [comment] 2019-12-29 03:15
@MorningstarZhang Then the issue should be related with shared memory on multi-process. I am afraid that I cannot help because the issue is on Python/windows side.

**Comment by HaoerSlayer** [comment] 2019-12-29 03:51
@Lyken17 
That`s OK. I have made some changes to the folder2lmdb.py so that it can run without error even num_worker is set to more than 0  and at least it can meet my need now.

**Comment by Lyken17** [comment] 2020-01-08 07:38
Close this issue since the problem was solved. Feel free to re-open if necessary.

**Closed as completed by Lyken17** 2020-01-08 07:38 UTC
